---
name:             ItemPopup
main:             presentkim\itempopup\ItemPopupMain
version:          1.2.0
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

permissions:
  itempopup.cmd:
    description:  ItemPopup main command
    default:      op
    children:
      itempopup.cmd.set:
        description:  ItemPopup command - set
        default:      op
      itempopup.cmd.remove:
        description:  ItemPopup command - remove
        default:      op
      itempopup.cmd.list:
        description:  ItemPopup command - list
        default:      op
      itempopup.cmd.lang:
        description:  ItemPopup command - lang
        default:      op
      itempopup.cmd.reload:
        description:  ItemPopup command - reload
        default:      op
      itempopup.cmd.save:
        description:  ItemPopup command - save
        default:      op
...
