---
name:             ItemPopup
main:             presentkim\itempopup\ItemPopupMain
version:          0.0.5
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

permissions:
  itempopup.cmd:
    description:  ItemPopup Command
    default:      op
...