---
name:             ItemPopup
main:             kim\present\itempopup\ItemPopup
version:          1.2.1
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/ItemPopup
description:      A plugin show custom item popup

permissions:
  itempopup.cmd:
    description:  ItemPopup main command
    default:      op
    children:
      itempopup.cmd.set:
        description:  ItemPopup command - set
        default:      op
      itempopup.cmd.remove:
        description:  ItemPopup command - remove
        default:      op
      itempopup.cmd.list:
        description:  ItemPopup command - list
        default:      op
      itempopup.cmd.lang:
        description:  ItemPopup command - lang
        default:      op
      itempopup.cmd.reload:
        description:  ItemPopup command - reload
        default:      op
      itempopup.cmd.save:
        description:  ItemPopup command - save
        default:      op
...
