name:             ItemPopup
main:             itempopup\ItemPopupMain
version:          0.0.4
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

commands:
  itempopup:
    description:  "ItemPopup command"
    permission:   itempopup.cmd
    usage:        "/ItemPopup <Set | Remove | List> <ItemID> <ItemDamage> [PopupText |  | Page]"

permissions:
  itempopup.cmd:
    description:  ItemPopup Command
    default:      op
